### ISSUE TITLE
Add Dataset for other countries

### ISSUE THREAD

**Issue by k3ii** [nicolasstrands/mauritius-public-holidays-dataset#2]
Hello @nicolasstrands ,
Could you please add dataset for:
* South Africa: https://www.gov.za/about-sa/public-holidays
* France: https://www.service-public.fr/particuliers/vosdroits/F24496?lang=en

**Comment by nicolasstrands** [comment]
Thanks for the suggestion, found a way to implement it!
Although perhaps not sure if that was the best way 😅 but it worked
